// <auto-generated />
using System;
using DocsUnmessed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocsUnmessed.Data.Migrations
{
    [DbContext(typeof(DocsUnmessedDbContext))]
    [Migration("20251231143810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DocsUnmessed.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("Action");

                    b.HasIndex("Success");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.DuplicateEntity", b =>
                {
                    b.Property<string>("DuplicateGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("DuplicateGroupId");

                    b.HasIndex("FileCount");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Duplicates");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.DuplicateItemEntity", b =>
                {
                    b.Property<string>("DuplicateGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("DuplicateGroupId", "ItemId");

                    b.HasIndex("DuplicateGroupId");

                    b.HasIndex("ItemId");

                    b.ToTable("DuplicateItems");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.ItemEntity", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AccessedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Attributes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("Extension")
                        .HasFilter("Extension IS NOT NULL");

                    b.HasIndex("Hash")
                        .HasFilter("Hash IS NOT NULL");

                    b.HasIndex("ModifiedUtc");

                    b.HasIndex("Path");

                    b.HasIndex("ScanId");

                    b.HasIndex("SizeBytes");

                    b.HasIndex("Type");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.MigrationOperationEntity", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("MigrationOperations");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.MigrationPlanEntity", b =>
                {
                    b.Property<string>("PlanId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedOperations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FailedOperations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metrics")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalOperations")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PlanId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScanId");

                    b.HasIndex("Status");

                    b.ToTable("MigrationPlans");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.RuleEntity", b =>
                {
                    b.Property<string>("RuleId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("Priority", "IsEnabled");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.ScanEntity", b =>
                {
                    b.Property<string>("ScanId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFolders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ScanId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.SuggestionEntity", b =>
                {
                    b.Property<string>("SuggestionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ConflictPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasons")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("SuggestionId");

                    b.HasIndex("Confidence");

                    b.HasIndex("ItemId");

                    b.HasIndex("RuleId");

                    b.HasIndex("ScanId");

                    b.HasIndex("Status");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.DuplicateItemEntity", b =>
                {
                    b.HasOne("DocsUnmessed.Data.Entities.DuplicateEntity", "DuplicateGroup")
                        .WithMany("DuplicateItems")
                        .HasForeignKey("DuplicateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsUnmessed.Data.Entities.ItemEntity", "Item")
                        .WithMany("DuplicateItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuplicateGroup");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.ItemEntity", b =>
                {
                    b.HasOne("DocsUnmessed.Data.Entities.ScanEntity", "Scan")
                        .WithMany("Items")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.MigrationOperationEntity", b =>
                {
                    b.HasOne("DocsUnmessed.Data.Entities.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("DocsUnmessed.Data.Entities.MigrationPlanEntity", "Plan")
                        .WithMany("Operations")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.MigrationPlanEntity", b =>
                {
                    b.HasOne("DocsUnmessed.Data.Entities.ScanEntity", "Scan")
                        .WithMany("MigrationPlans")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.SuggestionEntity", b =>
                {
                    b.HasOne("DocsUnmessed.Data.Entities.ItemEntity", "Item")
                        .WithMany("Suggestions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsUnmessed.Data.Entities.RuleEntity", "Rule")
                        .WithMany("Suggestions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocsUnmessed.Data.Entities.ScanEntity", "Scan")
                        .WithMany("Suggestions")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Rule");

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.DuplicateEntity", b =>
                {
                    b.Navigation("DuplicateItems");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.ItemEntity", b =>
                {
                    b.Navigation("DuplicateItems");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.MigrationPlanEntity", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.RuleEntity", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("DocsUnmessed.Data.Entities.ScanEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MigrationPlans");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
